use_frameworks!

target 'LazySettings_Example', :exclusive => true do
  pod 'LazySettings', :path => '../'
end

target 'LazySettings_Tests', :exclusive => true do
  pod 'LazySettings', :path => '../'

  
end
